# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jaxee' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jaxee

  target 'jaxeeTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crash'
  pod 'Firebase/Storage'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/RemoteConfig'

end

target 'jaxee-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jaxee-tvOS

  target 'jaxee-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


